### ISSUE TITLE
How use this?

### ISSUE THREAD

**Issue by carrieroent** [iamdb/hifi.rs#125]
Hey! I installed this (extracted the tar, copied the binary to my PATH and gave execute permissions), but I dont know, how use this? :D What are first steps that I have to do?
I just ran hifi-rs config username, hifi-rs config password and then hifi-rs play, but hifi-rs play or search or anything else doesn't work.

What causes database errors?

Where this store its configuration?

---
Thanks so much for this! This is a big favor for Qobuz on Linux.

**Comment by iamdb** [comment]
Sorry, I think I got confused between issues. Were you able to get the player to work?

**Comment by carrieroent** [comment]
I couldn't get this to work and I don't know how to use this, but I know how to _install_ programs such this and I was able to do a PR already. The reason for [the PR](https://github.com/iamdb/hifi.rs/pull/124) was [this](https://www.reddit.com/r/qobuz/comments/11s6kxt/comment/jcdl4cm/).

**Comment by iamdb** [comment]
I updated the README with some extra instructions. Can you see if those steps work better? If not, can you tell me the steps you took and the error you received?

And thank you for the link! I had no idea that was there. :-)

**Comment by carrieroent** [comment]
> I updated the README with some extra instructions. Can you see if those steps work better? If not, can you tell me the steps you took and the error you received?

Thank you very much! I will test.

> The config should be stored in ~/.local/share/hifi-rs/.
> 
> However, you run it with RUST_LOG=hifi_rs hifi-rs, it should log the database location definitively.

This could also be added to the README.

**Comment by iamdb** [comment]
Sorry, but can we keep the conversation to this issue? I'm getting confused having to answer all of them.

To answer your question about the API, I do not have keys. It logs in through the website and uses the token from there. I [ported over code](https://github.com/iamdb/hifi.rs/blob/dc639af8e678eddaffe21c4a960b972764f123fe/qobuz-api/src/client/api.rs#L641) from another project written in python.

**Comment by carrieroent** [comment]
> Sorry, but can we keep the conversation to this issue? I'm getting confused having to answer all of them.

I'm sorry for "bombarding" you with these. So much new and interesting... But I didn't deviate (only [this](https://github.com/iamdb/hifi.rs/issues/127#issuecomment-1475514675)) much from the topic.

> To answer your question about the API, I do not have keys. It logs in through the website and uses the token from there. I [ported over code](https://github.com/iamdb/hifi.rs/blob/dc639af8e678eddaffe21c4a960b972764f123fe/qobuz-api/src/client/api.rs#L641) from another project written in python.

Oh. Do you know, does librespot uses API keys or this kind of website login and take token way? As far as I know, they somehow got the API keys from the official client, could we do something similar?

**Comment by iamdb** [comment]
I don't know librespot uses off the top of my head. I'm sure if you browsed the repo, you could find out.
