### ISSUE TITLE
Rename to qobuz-tui or qobuz-cli

### ISSUE THREAD

**Issue by carrieroent** [iamdb/hifi.rs#126]
Just a suggestion, rename this to qobuz-tui or other qobuz-something. It would be easier to remember. What is the purpose of hifi-rs (hifi rust?)?

**Comment by iamdb** [comment]
Thank you, but I am going to leave the name. I do not want people to think I am associated with Qobuz and the player can potentially support other services so it may not always be just a Qobuz-based application.

hifi is short for ["high fidelity"](https://en.wikipedia.org/wiki/High_fidelity). It's to highlight the high resolution capabilities of the player.

**Comment by carrieroent** [comment]
Sorry if I'm being rude, but I think it would be best if this were broken down into the following parts:

- libqobuz, an open-source library for the internal, private API of Qobuz
- qobuz-cli/-tui, dedicated Qobuz CLI client, powered by libqobuz. The code base taken from the following.
- hifi.rs, a generic CLI music player, powered by libqobuz and others. Although I honestly doubt the need for this, because we have [termusic](https://github.com/tramhao/termusic) and others, but I don't want to discourage. Do what do you want! :)

**Comment by iamdb** [comment]
It pretty much already exists in that form.

`qobuz-api` is what you're calling `libqobuz`. The TUI and the CLI are just in the same codebase. I don't see a need toe split those at this point.

`librespot` is more than just an api client as it provides audio playback functionality as well.

**Comment by carrieroent** [comment]
> qobuz-api is what you're calling libqobuz. The TUI and the CLI are just in the same codebase. I don't see a need toe split those at this point.

Yes, but split these to separate repositories is better experience for library users. However, you're right that perhaps at this point there is no need to do this yet.

> librespot is more than just an api client as it provides audio playback functionality as well.

Of course we should bring the corresponding features to here. Don't we support playback?

And I still think there is a demand for a dedicated Qobuz CLI client. Bringing Qobuz support to CLI, general music players is pretty trivial once we have the library.

**Comment by iamdb** [comment]
> Of course we should bring the corresponding features to here. Don't we support playback?

Yes. That is my point. This already does a lot of things you're asking about.
