### ISSUE TITLE
How this works?

### ISSUE THREAD

**Issue by carrieroent** [iamdb/hifi.rs#127]
How this works? Does this use reversed the internal, private API of the [Qobuz official web client](https://play.qobuz.com)? So does this work exactly the same as [librespot](https://github.com/librespot-org/librespot)?

"Qobuz only supports Linux through the browser and _has no officially supported API_."?

**Comment by iamdb** [comment]
Looks like you got it figured out. Thank you for writing up those instructions.

This works similar to librespot, but it's not a libarary that can be used in other applications like librespot. Only the api client is a library crate.

**Comment by carrieroent** [comment]
> Looks like you got it figured out. Thank you for writing up those instructions.

How did you get the API keys from Qobuz web client?

> This works similar to librespot, but it's not a libarary that can be used in other applications like librespot. Only the api client is a library crate.

I understand, but the action is the same. Could you separate this into client and library, to two separate repository? It could accelerate integrating Qobuz to music players.

**Comment by carrieroent** [comment]
"Qobuz only supports Linux through the browser and has no _officially supported API_."? Does Qobuz have an API for third parties that they just don't support?

**Comment by iamdb** [comment]
See here https://github.com/iamdb/hifi.rs/issues/125#issuecomment-1475451158

**Comment by carrieroent** [comment]
_From https://github.com/iamdb/hifi.rs/issues/125#issuecomment-1475438305_: 
Question: Do you know why Deezer or Tidal don't have such this? They are quite popular. Is there any technical obstacle in them?

**Comment by iamdb** [comment]
I don't know if those services would work.
