### ISSUE TITLE
What are these snapshots?

### ISSUE THREAD

**Issue by carrieroent** [iamdb/hifi.rs#128]
https://github.com/iamdb/hifi.rs/tree/main/qobuz-api/src/client/snapshots

**Comment by iamdb** [comment]
Those are for testing to make sure the api client still works.

**Comment by carrieroent** [comment]
Are those complete snapshot of the Qobuz API and how did you do it?

**Comment by iamdb** [comment]
No, it's just for the types that are there. I'm sure there are things I am not using.

It logs in through the website and uses the token from there. I [ported over code](https://github.com/iamdb/hifi.rs/blob/dc639af8e678eddaffe21c4a960b972764f123fe/qobuz-api/src/client/api.rs#L641) from another project written in python.
