### ISSUE TITLE
Install doesnt seem to work on Fedora Linux

### ISSUE THREAD

**Issue by Blue-Hair-Miku** [iamdb/hifi.rs#144]
The install process seems foolproof, but for some reason isn't working for me. I download version 0.1.4, extract the tar, right click the file, and click execute. Nothing seems to happen after that. Am I missing a step?

**Comment by iamdb** [comment]
Does't give an error message at all? I have a laptop with Fedora, I'll give it a whirl.

Thanks for letting me know!

**Comment by Blue-Hair-Miku** [comment]
Absolutely nothing happens.
I also noticed the other method of installing, "or copy it to the your $PATH."
How do I try this?

**Comment by Blue-Hair-Miku** [comment]
Nevermind, i got it. The fix is copying the executable to /home/(user)/.local/bin/

One more question though. On the same fedora system, My ifi zen dac v2 displays a yellow circle while playing, indicating that it's receiving a 44.1-48 khz audio file. should I be concerned about this or is it expected? Sorry for the trouble.

**Comment by iamdb** [comment]
Oh,nice. Glad you got it working.

I'm not 100% sure about the other problem as it could be a few different things.

Are you using pulseaudio or pipewire? I know for pipewire you can use `pw-top` to see what format it's running at. It could help narrow down where the problem resides. Pulseaudio probably has a way of doing that as well, I just don't remember where, exactly.

If everything looks good there, then it should be working properly. If you're connecting through optical or something other than USB it may need further configuration as well, but I'm not sure about that.

**Comment by Blue-Hair-Miku** [comment]
![image](https://user-images.githubusercontent.com/110516756/230508003-8a103236-db3b-4a77-a203-e0c4b39b23fb.png)
the song being played here is at 96khz, and that matches up with pw-top. However, the dac is reporting a rate of 48000? Dac is connected with USB.

**Comment by Blue-Hair-Miku** [comment]
I think you just solved the issue. Thanks so much!

**Comment by iamdb** [comment]
Awesome!

**Comment by LTSCommerce** [comment]
loving this little app. Whilst the pipewire/fedora HD audio issues aren't directly related, I bet there are others of us out there who find this info useful. A little note in the main docs might be an idea to help us enable full quality audio, even just a link to this ticket
