### ISSUE TITLE
Feature Suggestion - Browser Plugin to Allow Control from Qobuz Web

### ISSUE THREAD

**Issue by LTSCommerce** [iamdb/hifi.rs#153]
A browser plugin that would intercept qobuz web player play button presses and instead trigger this app to play the album/track/playlist

I have a feeling this is doable, but I'm not quite sure how

I'm thinking along the lines of:

custom protocol handler (not sure how to do this in Wayland, but I recall doing it in older desktops) that fires up the player

some JS injected by the extension that will convert the play event into hitting the custom protocol URL

**Comment by iamdb** [comment]
I've been working on a bit of a refactor of the player to improve stability and part of that is updating the player and mpris metadata through notifications. As part of this, I was considering adding a websocket interface as an optional way to interact with the player.

It could be possible to connect to and interact with the player from the exension through this websocket interface.
