### ISSUE TITLE
Playlists pausing after every track

### ISSUE THREAD

**Issue by eldorel** [iamdb/hifi.rs#159]
As the title says, hifi.rs is stopping playback after each track in my playlist, requiring my to select the terminal window it's running from and hit space to start the next song. 

I started with "hifi-rs my-playlists" selected the playlist I wanted, then selected 'play'. 
The playlist's tracks are visible in the now-playing tab, when a song ends another track is moved to the current track info panel, but playback of the new track will not start without input.

Edit: after manually starting a handful of tracks (10 of 268), I just had one where it was able to start automatically. So apparently it's inconsistent.

**Comment by iamdb** [comment]
Thank you for letting me know. It's a feature I do not use often.

I am working on a refactor of the player and UI that should address this and will be ready soon.

**Comment by eldorel** [comment]
That's awesome to hear. 
If there's a beta or a point where you need testing on the refactored branch let me know i and I can try to build and test it on my system.  

also, for extra debugging info in case it helps:  the  play --uri  option from the cli consistently exhibits the 'pause after each track' behavior. 
However, it seems to be more constant with a few of my longer playlists (pausing after every track), but is less consistent will smaller lists (pausing every two or three tracks). 
    (the most consistently-paused one is ~260 tracks, and the other is only 57)

**Comment by eldorel** [comment]
Testing with 0.2.1, the issue is still present. No apparent change to symptoms.

**Comment by iamdb** [comment]
Can you share the playlist?

**Comment by eldorel** [comment]
Sure. 
This is the long one.   
     https://play.qobuz.com/playlist/7892923

An additional detail I forgot to mention previously is that after the unwanted pausing, hitting space on the terminal window will occasionally advance the 'now playing' track display, but restart the previous track.

**Comment by iamdb** [comment]
Thanks for sharing. There are defininitely some issues, but I am not sure what's causing them yet.

Are there any playlists with fewer tracks that play ok? Does this one plays ok at first and then have these problems? 

I can play the playlist and it skips tracks fine, but when I try to skip ahead to something deep in the list it starts to have some issues.

**Comment by eldorel** [comment]
I've been testing a handful of them for the last hour, and it seems like all of them do it fairly frequently. 
This one is just a random one I imported into my playlists a while back and it only played the first track before pausing today. 
https://open.qobuz.com/playlist/5969067

I'm not going to say that it's 100% not something on my end triggering the effect, but it's consistent across a few different systems (all running linux, either the latest ubuntu or linuxmint so far, but I can arrange to test on pretty much anything).

**Comment by iamdb** [comment]
`HIFIRS_LOG=trace` should do the trick, but it competes with the UI at times.

I'm going to have it output to file, but do you mind if I post builds here to try? Will be much faster than making releases.

**Comment by iamdb** [comment]
Also, I think it's somewhat related to that, but it does switch tracks ok on my end, just not past a certain point. I usually notice the `about-to-finish` fire around 5-10 seconds before the track finishes.

I'm unsure if it's related, but I can't load anything in that first playlist past track 258. I can skip forward all the way up to that track and then it stops working.

**Comment by eldorel** [comment]
Yeah, That 258 track limit seems to also apply to the official app. It's why that playlist isn't bigger. 
I tested with a few more while I was working, and even a list with only 50 tracks still pauses for me. 

It also pauses when I skip around or click on a track further ahead in the list. 

I'll test with the log enabled today and I have no problem testing builds for you.

**Comment by iamdb** [comment]
So weird about that track limit. I definitely don't use their service like most people because I use a playlist, but just as a list of albums to listen to, not tracks.

Based on the descriptions, it sounds like it's buffering a lot. I'll also add something so it shows when it's buffering a track to the UI. 

The buffering will pause the track and play it again when it's full. It will also start playing once it has enough buffer to do so. I believe it should output in the logs when it's buffering with a percent, too.

**Comment by iamdb** [comment]
There's a new release: https://github.com/iamdb/hifi.rs/releases/tag/v0.2.2

Buffering gets reported in the UI and tracing it output on stderr instead so it doesn't compete with the UI.

You can output it to file with something like: `cargo run --bin hifi-rs -- open 2>> out`

**Comment by eldorel** [comment]
Thank you very much. I'm outputting a debug log with the new release right now. 

Interestingly, it's playing the *completely* wrong track at the moment.
I've literally never heard this song before, but the player UI says it's playing track 2 of the 14 track playlist I grabbed. 

And then it paused at the end of that track. 

I notice that this log contains the user token and a lot of additional information, is there a way for me to sanitize it or a moderately secure method to send it to you?

**Comment by eldorel** [comment]
Here's the end of the file with the API request and the JSON from the last requests left out. 

That 'checking for expired' line is still continuing to be added about once every 90 seconds or so. 



>   2023-07-13T18:43:22.086330Z DEBUG cursive_core::views::linear_layout: Ideal result: XY { x: 8, y: 3 }
>     at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cursive_core-0.3.7/src/views/linear_layout.rs:526
> 
>   2023-07-13T18:43:22.194615Z DEBUG hifi_rs::player: END OF STREAM
>     at hifirs/src/player/mod.rs:725
>     in hifi_rs::player::player_loop with safe_player: RwLock { data: <locked> },    REDACTED
> 
>   2023-07-13T18:43:22.199534Z DEBUG hifi_rs::player: *** successful state change ***
>     at hifirs/src/player/mod.rs:151
>     in hifi_rs::player::set_player_state with self: Player REDACTED JSON
> 
> 
> 
> 
> 
>   2023-07-13T18:43:52.015021Z TRACE hyper::proto::h1::io: received 0 bytes
>     at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-0.14.26/src/proto/h1/io.rs:269
> 
>   2023-07-13T18:43:52.015047Z TRACE hyper::proto::h1::conn: found EOF on idle connection, closing
>     at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-0.14.26/src/proto/h1/conn.rs:393
> 
>   2023-07-13T18:43:52.015050Z TRACE hyper::proto::h1::conn: State::close_read()
>     at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-0.14.26/src/proto/h1/conn.rs:956
> 
>   2023-07-13T18:43:52.015054Z TRACE hyper::proto::h1::conn: flushed({role=client}): State { reading: Closed, writing: Init, keep_alive: Disabled }
>     at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-0.14.26/src/proto/h1/conn.rs:732
> 
>   2023-07-13T18:43:52.015099Z TRACE hyper::proto::h1::conn: shut down IO complete
>     at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-0.14.26/src/proto/h1/conn.rs:739
> 
>   2023-07-13T18:43:52.015110Z TRACE mio::poll: deregistering event source from poller
>     at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mio-0.8.8/src/poll.rs:662
> 
>   2023-07-13T18:44:51.337825Z TRACE hyper::client::pool: idle interval checking for expired
>     at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-0.14.26/src/client/pool.rs:767
> 
>   2023-07-13T18:44:51.337853Z TRACE hyper::client::pool: idle interval evicting closed for ("https", www.qobuz.com)
>     at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-0.14.26/src/client/pool.rs:458
> 
>   2023-07-13T18:46:21.337734Z TRACE hyper::client::pool: idle interval checking for expired
>     at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-0.14.26/src/client/pool.rs:767
> 
>   2023-07-13T18:47:51.337952Z TRACE hyper::client::pool: idle interval checking for expired
>     at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-0.14.26/src/client/pool.rs:767
> 
>   2023-07-13T18:49:21.337297Z TRACE hyper::client::pool: idle interval checking for expired
>     at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-0.14.26/src/client/pool.rs:767
>

**Comment by eldorel** [comment]
and for a quick reference later> 

export HIFIRS_LOG=trace

hifi-rs open 2>> hifi-log.txt

**Comment by iamdb** [comment]
Thank you! It definitely shouldn't be reaching end of stream.

This is a stupid question, but just want to rule it out because I'm unsure if the UX is good but when playing the playlist you see all the tracks in the now playing screen, right?

**Comment by eldorel** [comment]
I do, yes.

**Comment by eldorel** [comment]
Actually, looking at it, when I exited the app the playlist apparently changed in the UI.

I hadn't noticed earlier, but the terminal is still open.

This doesn't look like any of my lists, either.

**Comment by iamdb** [comment]
It changed in the Qobuz UI?

Do you mean the player changed the playlist within the Qobuz service? That definitely shouldn't happen since the player never hits those endpoints.

If you haven't already, would you mind deleting the database and starting fresh? I've really never seen it act this weird so I wonder if something got corrupted.

**Comment by eldorel** [comment]
I was referring to the hifirs player. 
I'd left the player open while I copied out the log entries above and formatted my comment, and then I closed the player and went back to focusing on work. 

But looking at the last frame of the player, the playlist shown is not the one I was playing, and the log says there was an api request and JSON reply right before the program exited.


And I used the 'reset' parameter previously, but I'll go deleted the DB manually and start it up again.

**Comment by eldorel** [comment]
Deleted db file, had to reset my password one song played, and the same results. 
    (btw the -u parameter in the help output doesn't work now, I had to use 'config username' )

**Comment by iamdb** [comment]
I'll check out that command.

I did some more poking around the playlist stuff and there's definitely some problems there. I'm not sure it fixes the core issue, but navigating the tracks, skipping forward/backward, etc. should be more reliable. The issue you were seeing with the wrong track should also be fixed.

https://github.com/iamdb/hifi.rs/releases/tag/v0.2.3

Still trying to reproduce the main issue.

**Comment by nmars-cloud** [comment]
eldorel the terminal what you using is the key try alacritty work like a charm

**Comment by eldorel** [comment]
Sorry for the delay, had a few things blow up and eat way too much time. 
Opening the new release with the 'open' argument automatically closes with a rust error, but using 'play --url ' works, so I was able to test. 

It still stops after a track. 
I'm wondering if there might be some dependence on a library for feature that I don't have (I am running an LTS build, so that's not unlikely.)

What system/distro are you using for testing? I can spin up a vm and test that and then start comparing configurations to see if the issue is a library or something weird related to the playback environment. 


As for terminal, I've previously tested with mate terminal, xterm, and wezterm all with the same pausing effect. 
I probably wouldn't mind using alacritty for a test, but the 'install' for my distro requires either setting up 'cargo' or building from source, and I honestly don't have time right now to figure out why the build fails.

**Comment by eldorel** [comment]
That same error also pops up randomly when skipping ahead to a different track: 

`thread 'tokio-runtime-worker' panicked at 'property 'instant-uri' of type 'GstPlayBin3' not found', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/glib-0.17.10/src/object.rs:2230:13
`

**Comment by iamdb** [comment]
No worries, I was away most of last week myself.

I use do use Arch (got me :-)) with the latest Gstreamer libs. The released app is built in GH actions using Ubuntu, but also installs all of the Gstreamer libs when doing so.

If those other gstreamer packages are not installed, try installing those and let me know how it goes. That `instant-uri` error definitely sounds like it doesn't have the right plugins. I'll also look into making a statically linked version.

**Comment by eldorel** [comment]
> eldorel install all gstreamer packages gstreamer gst-libav gst-plugins-bad good base ugly etc....

I went ahead and did this (actually ran an apt -s with a wildcard, so I could make sure I didn't miss anything.)

Same error on hifi-rs open or when clicking to a different track in a playlist. 

> 'property 'instant-uri' of type 'GstPlayBin3' not found'

And still pausing if I open the playlist with --url and let it run.

**Comment by iamdb** [comment]
Could you try this build?

[hifi-rs.zip](https://github.com/iamdb/hifi.rs/files/12164385/hifi-rs.zip)

**Comment by eldorel** [comment]
Still seeing the instant-uri error print to screen with 'hifi-rs open', but the client doesn't crash completely now.  
It never starts playing and doesn't accept most of the command input, but arrows allow me to move around in the playlist and Ctrl-C pulls up the quit dialog. 
Space/Tab/N/P/L/H all do nothing though. 

As before, using the 'Play --url' argument works and loads the player without any error. 

Letting the first track play through, I got the same error as above (and same effect on input afterword)

I also tested using 'play --url' and then immediately skipping ahead to the 15th track using the mouse.  The track I selected played without issue, and then the playlist jumped back to track 001 and paused itself.

**Comment by iamdb** [comment]
Thanks for the info! After doing more investigating on my end, I definitely think the issue is a conflict with the Gstreamer versions, but I'm having some trouble linking it all statically.

If you're running anything other than version 1.22 of gstreamer and can upgrade, I would give that a try. I'm going to keep trying to get the compilation to work or maybe put some version guards in the player code to prevent these issues.
