### ISSUE TITLE
crash on specific playlist

### ISSUE THREAD

**Issue by LTSCommerce** [iamdb/hifi.rs#161]
URL: https://play.qobuz.com/playlist/11398919

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/runner/work/hifi.rs/hifi.rs/hifirs/src/player.rs:630:61
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted (core dumped)
```

**Comment by iamdb** [comment]
Ah, looks like it's a playlist with some tracks unplayable. Definitely not a case I was expecting, but should be able to fix that.

Probably best to show the tracks as disabled and skip over them like in the web app.

**Comment by iamdb** [comment]
I believe this should also be fixed with the new release, but let me know if it still exists. The new behvior should show disabled tracks in the search/playlist lists, but when adding to the player it will strip out any unplayable tracks.
