### ISSUE TITLE
new UI - not sure how to play a playlist

### ISSUE THREAD

**Issue by LTSCommerce** [iamdb/hifi.rs#164]
So I'm finding the new UI is great, the search is very usable

For playlist though, I get to the playlist screen and I'm not sure how to actually play it. If it play the first track it seems to only do that - it doesn't queue the full playlist

There is a `<play>` at the top of the list, but clicking this doesn't seem to do anything

I've tried with smaller playlists to see if its just a "massive playlists are too big" kind of issue, but that doesn't seem to be the case.

Is this a PEBKAC or is there a real bug here?

**Comment by LTSCommerce** [comment]
also note - I never really did anything other that use teh --uri functionality in the old version, but this new version UI has encouraged me to use it for navigation as well as playing and that's how I've discovered this issue

**Comment by iamdb** [comment]
It's definitely not on your end. :-) Should have a fixed version up shortly.

**Comment by iamdb** [comment]
This should be fixed.

https://github.com/iamdb/hifi.rs/releases/tag/v0.2.1

**Comment by LTSCommerce** [comment]
sorted :)
