### ISSUE TITLE
albmum metadata missing when playing a playlist

### ISSUE THREAD

**Issue by LTSCommerce** [iamdb/hifi.rs#167]
I've just got around to [hooking up rescrobbled](https://github.com/LongTermSupport/fedora-desktop/blob/main/playbooks/imports/optional/play-qobuz-cli.yml)

However  its failing when playling a playlist due to the meta data for album being missing

I can see this with my trusty loop:

```
while true; do playerctl metadata --format "Now playing: {{ artist }} - {{ album }} - {{ title }}"; sleep 60;echo; echo; echo; done
```

that I use for being able to copy/paste whats playing - the album is now missing. 

This is when playing a playlist. When playing an album, the meta data is there

Is this a limitation of the Qobuz API, or a bug?

**Comment by iamdb** [comment]
This is probably just something with the mpris metadata exporting. I'll take a look.

**Comment by iamdb** [comment]
This should be fixed on the latest release: https://github.com/iamdb/hifi.rs/releases/tag/v0.2.2

**Comment by LTSCommerce** [comment]
confirmed fixed on 0.2.3

thanks very much :+1:

**Comment by LTSCommerce** [comment]
reopening this ticket as I think it's possibly related

just noticed that rescrobbled is failing to scrobble anyhting at all now, this is with 0.3.3

Oct 26 11:05:14 Chromecast-Audio.famedmonds.house rescrobbled[3993]: Cannot submit track without album to Last.fm
Oct 26 11:07:42 Chromecast-Audio.famedmonds.house rescrobbled[3993]: Cannot submit track without album to Last.fm
Oct 26 11:10:09 Chromecast-Audio.famedmonds.house rescrobbled[3993]: Now playing: Myselor - Soul Power----
Oct 26 11:10:09 Chromecast-Audio.famedmonds.house rescrobbled[3993]: Cannot submit track without album to Last.fm

This is when playing an album which I would have thought would be fine 
https://play.qobuz.com/album/fjkjrj6yqm4db

Seems I have nothing being scrobbled at the moment. It's nto the end of the world, but I do like having this record of stuff I've listened to as I listen to a LOT of different stuff and its handy to be able to refind things easily

**Comment by iamdb** [comment]
Thanks! I'll have a look.

**Comment by iamdb** [comment]
Can you verify this is corrected in the latest version?

**Comment by LTSCommerce** [comment]
```
$hifi-rs --version
hifi-rs 0.3.4
```
Also - noticed this - album is empty when using playerctl

```
$ playerctl metadata --format "Now playing: {{ artist }} - {{ album }} - {{ title }}"
Now playing: Charli Brix -  - Fifty Fifty
```

**Comment by LTSCommerce** [comment]
Just realised you have released a new version hours ago - I've now updated and playerctl is showing album data

```
playerctl metadata --format "Now playing: {{ artist }} - {{ album }} - {{ title }}"
Now playing: Charli Brix - The Art of Change - Be There
```

And rescrobbled seems happy again :)

```
systemctl --user status rescrobbled.service 
● rescrobbled.service - An MPRIS scrobbler
     Loaded: loaded (/home/joseph/.config/systemd/user/rescrobbled.service; enabled; preset: disabled)
    Drop-In: /usr/lib/systemd/user/service.d
             └─10-timeout-abort.conf
     Active: active (running) since Tue 2023-10-31 07:01:20 GMT; 1 day 3h ago
       Docs: https://github.com/InputUsername/rescrobbled
   Main PID: 9417 (rescrobbled)
     CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/rescrobbled.service
             └─9417 /home/joseph/.local/bin/rescrobbled

Nov 01 10:30:06 fedora rescrobbled[9417]: Cannot submit track without album to Last.fm
Nov 01 10:31:47 fedora rescrobbled[9417]: Now playing: Charli Brix - Reminisce----
Nov 01 10:31:47 fedora rescrobbled[9417]: Cannot submit track without album to Last.fm
Nov 01 10:34:00 fedora rescrobbled[9417]: Cannot submit track without album to Last.fm
Nov 01 10:34:51 fedora rescrobbled[9417]: Now playing: Charli Brix - Fifty Fifty----
Nov 01 10:34:51 fedora rescrobbled[9417]: Player hifi-rs stopped, looking for a new MPRIS player...
Nov 01 10:35:47 fedora rescrobbled[9417]: Found active player hifi-rs
Nov 01 10:35:47 fedora rescrobbled[9417]: ----
Nov 01 10:35:47 fedora rescrobbled[9417]: Now playing: Charli Brix - Be There (The Art of Change)
Nov 01 10:35:47 fedora rescrobbled[9417]: Status updated on Last.fm successfully
````

**Comment by LTSCommerce** [comment]
thank @iamdb :+1:
