### ISSUE TITLE
Feature Request - ability to paste URI into the new UI and play it

### ISSUE THREAD

**Issue by LTSCommerce** [iamdb/hifi.rs#168]
The new UI is great, but I still like to use the web player to find stuff

When I do find somerthing, I have to kill hifi-rs and relaunch to play the URI

Woudl be nice if it was possible to paste a URI in to the UI somewhere directly - maybe the search box, or maybe just recieve URI from stdin somehow and automatically start playing it?

**Comment by iamdb** [comment]
I could add an "Open Link" item to the menu that pops up a window to enter the url. Then if you press enter it will play it. Maybe also tie it to the `O` key as a shortcut.

As far as playing something outside of the player, you can also start playing something via `mpris`.

`playerctl open <qobuz url>` should do the trick, assuming the player is already open.

At some point I plan to add the ability to control an already running instance from the same CLI.
