### ISSUE TITLE
0.2.4 not playing at all

### ISSUE THREAD

**Issue by LTSCommerce** [iamdb/hifi.rs#171]
Let me know if there's a way I can give you some debug output etc

But 0.2.4 just does not play

**Comment by LTSCommerce** [comment]
downgraded to 0.2.3 and it is playing

**Comment by iamdb** [comment]
Damn. That's unfortunate. When it doesn't play, is that literally it? You hit play and it just sits there?

Does the app or UI freeze or anything?

**Comment by LTSCommerce** [comment]
Yeah it just doesn't do anything. I think the icon changes to indicate its trying to play, but that's it

I can reinstall if you want me to try some more stuff, or let me know if I can generate you some useful logs somehow

**Comment by iamdb** [comment]
Sorry for the delay, I was out of town for most of last week.

You're on Fedora, right? Gonna setup a VM and try with a fresh install.

**Comment by LTSCommerce** [comment]
On Fedora yes

However - I was listening to 0.2.3 yesterday and had the same thing happen - all audio stopped. In the end I restarted all the pipewire related services and that fixed it.

I think it was just a fluke that when I installed 0.2.4 I must have had this same pipeware flake out immediately after. I've now reinstalled 0.2.4 and it is working fine  :+1: 

Please regard this issue as closed - nothing to do with hifi-rs, something up with pipewire

**Comment by LTSCommerce** [comment]
OK might have spoken too soon 

Upgraded to 0.2.4 and I'm now getting the "it just wont play" bug again

Have restarted pipewire etc 

```
systemctl --user restart pipewire wireplumber pipewire-pulse
```

Turns out, it only seems to refuse to play some stuff

This album in particular I could not get 0.2.4 to play

https://play.qobuz.com/album/wj3kcoe0s21uc

Downgraded to 0.2.3 and it plays. There's something weird going on

**Comment by iamdb** [comment]
Can you tell me what version of Gstreamer is installed?

**Comment by iamdb** [comment]
Also, could you try this build?

[hifi-rs.zip](https://github.com/iamdb/hifi.rs/files/12164385/hifi-rs.zip)

**Comment by LTSCommerce** [comment]
```
joseph@fedora dnf list installed | grep gstreamer
PackageKit-gstreamer-plugin.x86_64                   1.2.6-6.fc38                        @anaconda                                 
gstreamer1.x86_64                                    1.22.4-1.fc38                       @updates                                  
gstreamer1-devel.x86_64                              1.22.4-1.fc38                       @updates                                  
gstreamer1-doc.noarch                                1.22.3-1.fc38                       @updates                                  
gstreamer1-plugin-libav.x86_64                       1.22.3-1.fc38                       @updates                                  
gstreamer1-plugin-openh264.x86_64                    1.22.1-1.fc38                       @fedora-cisco-openh264                    
gstreamer1-plugins-bad-free.x86_64                   1.22.3-1.fc38                       @updates                                  
gstreamer1-plugins-bad-free-devel.x86_64             1.22.3-1.fc38                       @updates                                  
gstreamer1-plugins-bad-free-extras.x86_64            1.22.3-1.fc38                       @updates                                  
gstreamer1-plugins-base.x86_64                       1.22.3-1.fc38                       @updates                                  
gstreamer1-plugins-base-devel.x86_64                 1.22.3-1.fc38                       @updates                                  
gstreamer1-plugins-base-tools.x86_64                 1.22.3-1.fc38                       @updates                                  
gstreamer1-plugins-good.x86_64                       1.22.3-1.fc38                       @updates                                  
gstreamer1-plugins-good-extras.x86_64                1.22.3-1.fc38                       @updates                                  
gstreamer1-plugins-good-gtk.x86_64                   1.22.3-1.fc38                       @updates                                  
gstreamer1-plugins-good-qt.x86_64                    1.22.3-1.fc38                       @updates                                  
gstreamer1-plugins-ugly.x86_64                       1:1.22.3-1.fc38                     @rpmfusion-free-updates                   
gstreamer1-plugins-ugly-free.x86_64                  1.22.3-1.fc38                       @updates                                  
pipewire-gstreamer.x86_64                            0.3.74-1.fc38                       @updates      ```

**Comment by LTSCommerce** [comment]
running that build now, so far so good

**Comment by iamdb** [comment]
Great, thanks for letting me know. I think the issue is with Gstreamer versions between systems and how it gets compiled for the Github release. It's why others are having so many issues I'm not seeing on my system. I'm going to keep trying to get the static build together to fix it.
