### ISSUE TITLE
`hifi-rs config username` and `hifi-rs config password` do not insert anything into the database

### ISSUE THREAD

**Issue by PatrickJosh** [iamdb/hifi.rs#196]
Hey,
when starting the player, although having set username and password, I get the following error:

```
023-09-06T10:43:04.264626Z ERROR hifirs_qobuz_api::client::api: no app_id
```

I have discovered that the database's config table did not contain any rows. After having inserted my username and password manually into the table using the sqlite3 command line tool, the player works just fine. Hence, I suggest that the `username` and `password` sub-options of `config` might not work correctly.
This happened with both the pre-compiled binary from Github and my self-compiled binary, both being version 0.3.1.

**Comment by iamdb** [comment]
Sorry about that. Thank you for letting me know. I'll have a look.
